stages:
  - test
  - deploy

test:
  stage: test
  script: bash test.sh
  tags:
    - wen

deploy_staging:
  stage: deploy
  script:
    - bash prod.sh up
  environment:
    name: staging
    url: https://wen.moiden.com
  when: manual
  tags:
    - stage
