stages:
  - test
  - deploy

test:
  stage: test
  script: bash test.sh
  tags:
    - wen

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://wen.moiden.com
  when: manual
  only:
    - master
  tags:
    - wen
    - stage
