version: '2'

services:
  api:
    build:
      context: .
      dockerfile: ./dockerfiles/prod/Dockerfile
    env_file: .env.prod
    command: yarn run api

  static:
    build:
      context: .
      dockerfile: ./dockerfiles/prod/Dockerfile
    env_file: .env.prod
    command: yarn run static

  socket:
    build:
      context: .
      dockerfile: ./dockerfiles/prod/Dockerfile
    env_file: .env.prod
    command: yarn run socket

  runner:
    build:
      context: .
      dockerfile: ./dockerfiles/prod/Dockerfile
    env_file: .env.prod
    depends_on:
      - api
      - socket
      - static
      - nginx
    command: yarn run bootstrap

  nginx:
    ports:
      - '3000:3000'

  postgres:
    env_file: .env.prod
